databases:
  - name: Budget-app
    databaseName: budget_app_2rsn
    user: budget_app_2rsn_user

services:
  - type: web
    name: budget_app_shalini
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget_app_2rsn
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false